Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Python_django\lection\myproject\myapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2169
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2220
Not Found: /
"GET / HTTP/1.1" 404 2169
Not Found: /
"GET / HTTP/1.1" 404 2169
Not Found: /
"GET / HTTP/1.1" 404 2169
"GET /prefix/about/ HTTP/1.1" 200 27
"GET /prefix/about/ HTTP/1.1" 200 27
"GET /prefix HTTP/1.1" 301 0
"GET /prefix/ HTTP/1.1" 200 13
"GET /prefix/ HTTP/1.1" 200 13
D:\Python_django\lection\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Index page accessed
"GET /prefix/ HTTP/1.1" 200 13
Index page accessed
"GET /prefix/ HTTP/1.1" 200 13
Error in about page: division by zero
Traceback (most recent call last):
  File "D:\Python_django\lection\myproject\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
"GET /prefix/about/ HTTP/1.1" 200 27
Error in about page: division by zero
Traceback (most recent call last):
  File "D:\Python_django\lection\myproject\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
"GET /prefix/about/ HTTP/1.1" 200 27
D:\Python_django\lection\myproject\myproject\settings.py changed, reloading.
INFO 2023-08-27 15:24:06,451 autoreload 16944 7408 Watching for file changes with StatReloader
ERROR 2023-08-27 15:24:10,390 views 16944 2428 Error in about page: division by zero
Traceback (most recent call last):
  File "D:\Python_django\lection\myproject\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
INFO 2023-08-27 15:24:10,393 basehttp 16944 2428 "GET /prefix/about/ HTTP/1.1" 200 27
ERROR 2023-08-27 15:24:11,537 views 16944 17440 Error in about page: division by zero
Traceback (most recent call last):
  File "D:\Python_django\lection\myproject\myapp\views.py", line 17, in about
    result = 1 / 0
ZeroDivisionError: division by zero
INFO 2023-08-27 15:24:11,539 basehttp 16944 17440 "GET /prefix/about/ HTTP/1.1" 200 27
INFO 2023-08-27 15:24:14,467 views 16944 2428 Index page accessed
INFO 2023-08-27 15:24:14,469 basehttp 16944 2428 "GET /prefix/ HTTP/1.1" 200 13
INFO 2023-08-27 15:24:14,571 views 16944 17440 Index page accessed
INFO 2023-08-27 15:24:14,574 basehttp 16944 17440 "GET /prefix/ HTTP/1.1" 200 13
INFO 2023-09-03 14:16:39,730 autoreload 708 8320 Watching for file changes with StatReloader
INFO 2023-09-03 14:17:28,278 autoreload 708 8320 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-03 14:17:30,016 autoreload 5296 1364 Watching for file changes with StatReloader
WARNING 2023-09-03 14:17:30,628 log 5296 17520 Not Found: /heads/
WARNING 2023-09-03 14:17:30,631 basehttp 5296 17520 "GET /heads/ HTTP/1.1" 404 2205
WARNING 2023-09-03 14:17:32,087 log 5296 16156 Not Found: /heads/
WARNING 2023-09-03 14:17:32,090 basehttp 5296 16156 "GET /heads/ HTTP/1.1" 404 2205
WARNING 2023-09-03 14:17:33,794 log 5296 19268 Not Found: /
WARNING 2023-09-03 14:17:33,796 basehttp 5296 19268 "GET / HTTP/1.1" 404 2169
WARNING 2023-09-03 14:17:34,081 log 5296 16156 Not Found: /
WARNING 2023-09-03 14:17:34,084 basehttp 5296 16156 "GET / HTTP/1.1" 404 2169
INFO 2023-09-03 14:17:50,835 autoreload 5296 1364 D:\Python_django\dz\myproject\urls.py changed, reloading.
INFO 2023-09-03 14:17:52,174 autoreload 14048 10312 Watching for file changes with StatReloader
INFO 2023-09-03 14:17:56,176 views 14048 4672 Index page accessed
INFO 2023-09-03 14:17:56,180 basehttp 14048 4672 "GET / HTTP/1.1" 200 13
INFO 2023-09-03 14:17:56,312 views 14048 9516 Index page accessed
INFO 2023-09-03 14:17:56,319 basehttp 14048 9516 "GET / HTTP/1.1" 200 13
INFO 2023-09-03 16:58:44,478 autoreload 19928 17992 Watching for file changes with StatReloader
INFO 2023-09-03 16:58:48,544 views 19928 20160 Index page accessed
INFO 2023-09-03 16:58:48,554 basehttp 19928 20160 "GET / HTTP/1.1" 200 13
INFO 2023-09-03 16:58:50,003 views 19928 1320 Index page accessed
INFO 2023-09-03 16:58:50,005 basehttp 19928 1320 "GET / HTTP/1.1" 200 13
INFO 2023-09-03 16:58:56,494 basehttp 19928 7792 "GET /about HTTP/1.1" 301 0
DEBUG 2023-09-03 16:58:56,526 views 19928 7420 About page accessed
INFO 2023-09-03 16:58:56,527 basehttp 19928 7420 "GET /about/ HTTP/1.1" 200 23
DEBUG 2023-09-03 16:58:56,642 views 19928 14948 About page accessed
INFO 2023-09-03 16:58:56,647 basehttp 19928 14948 "GET /about/ HTTP/1.1" 200 23
INFO 2023-09-11 20:52:55,970 autoreload 32048 23200 Watching for file changes with StatReloader
INFO 2023-09-11 20:53:14,719 basehttp 32048 29928 "GET /about HTTP/1.1" 301 0
DEBUG 2023-09-11 20:53:14,929 views 32048 28676 About page accessed
INFO 2023-09-11 20:53:14,931 basehttp 32048 28676 "GET /about/ HTTP/1.1" 200 23
DEBUG 2023-09-11 20:53:17,592 views 32048 17420 About page accessed
INFO 2023-09-11 20:53:17,594 basehttp 32048 17420 "GET /about/ HTTP/1.1" 200 23
ERROR 2023-09-11 20:53:59,752 log 32048 6452 Internal Server Error: /products/3
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 28, in client_orders
    orders = Order.objects.filter(client=client, date_ordered__lt=NEED_THIS_DATE).all()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-09-11 20:53:59,759 basehttp 32048 6452 "GET /products/3 HTTP/1.1" 500 110947
ERROR 2023-09-11 20:54:00,827 log 32048 28860 Internal Server Error: /products/3
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 28, in client_orders
    orders = Order.objects.filter(client=client, date_ordered__lt=NEED_THIS_DATE).all()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-09-11 20:54:00,847 basehttp 32048 28860 "GET /products/3 HTTP/1.1" 500 109994
INFO 2023-09-11 20:58:40,910 autoreload 32048 23200 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-11 20:58:46,756 autoreload 22936 11692 Watching for file changes with StatReloader
ERROR 2023-09-11 20:59:03,911 log 22936 26728 Internal Server Error: /products/3
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 28, in client_orders
    orders = Order.objects.filter(client=client).all()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-09-11 20:59:03,920 basehttp 22936 26728 "GET /products/3 HTTP/1.1" 500 110522
ERROR 2023-09-11 20:59:10,395 log 22936 32244 Internal Server Error: /products/3
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 28, in client_orders
    orders = Order.objects.filter(client=client).all()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1426, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1236, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\query.py", line 1724, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2023-09-11 20:59:10,421 basehttp 22936 32244 "GET /products/3 HTTP/1.1" 500 109442
INFO 2023-09-19 16:58:07,594 autoreload 1896 2628 Watching for file changes with StatReloader
INFO 2023-09-19 16:58:12,511 views 1896 6624 Index page accessed
INFO 2023-09-19 16:58:12,518 basehttp 1896 6624 "GET / HTTP/1.1" 200 13
INFO 2023-09-19 16:58:14,895 views 1896 3672 Index page accessed
INFO 2023-09-19 16:58:14,897 basehttp 1896 3672 "GET / HTTP/1.1" 200 13
WARNING 2023-09-19 16:58:15,426 log 1896 5760 Not Found: /favicon.ico
WARNING 2023-09-19 16:58:15,428 basehttp 1896 5760 "GET /favicon.ico HTTP/1.1" 404 2822
WARNING 2023-09-19 16:58:18,806 log 1896 5760 Not Found: /sem3
WARNING 2023-09-19 16:58:18,807 basehttp 1896 5760 "GET /sem3 HTTP/1.1" 404 2801
WARNING 2023-09-19 16:58:19,042 log 1896 3672 Not Found: /sem3
WARNING 2023-09-19 16:58:19,045 basehttp 1896 3672 "GET /sem3 HTTP/1.1" 404 2801
ERROR 2023-09-19 16:58:28,910 log 1896 7748 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 16:58:28,924 basehttp 1896 7748 "GET /order_list HTTP/1.1" 500 67557
ERROR 2023-09-19 16:58:29,205 log 1896 8780 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 16:58:29,211 basehttp 1896 8780 "GET /order_list HTTP/1.1" 500 66612
WARNING 2023-09-19 16:58:37,678 log 1896 2388 Not Found: /sem3/order_list
WARNING 2023-09-19 16:58:37,679 basehttp 1896 2388 "GET /sem3/order_list HTTP/1.1" 404 2834
WARNING 2023-09-19 16:58:37,849 log 1896 10640 Not Found: /sem3/order_list
WARNING 2023-09-19 16:58:37,852 basehttp 1896 10640 "GET /sem3/order_list HTTP/1.1" 404 2834
ERROR 2023-09-19 16:58:41,143 log 1896 13784 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 16:58:41,145 basehttp 1896 13784 "GET /order_list HTTP/1.1" 500 67557
ERROR 2023-09-19 16:58:41,363 log 1896 9768 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 16:58:41,363 basehttp 1896 9768 "GET /order_list HTTP/1.1" 500 66612
INFO 2023-09-19 17:01:52,317 autoreload 14264 13936 Watching for file changes with StatReloader
INFO 2023-09-19 17:01:55,059 views 14264 11196 Index page accessed
INFO 2023-09-19 17:01:55,072 basehttp 14264 11196 "GET / HTTP/1.1" 200 13
INFO 2023-09-19 17:01:55,638 views 14264 12640 Index page accessed
INFO 2023-09-19 17:01:55,640 basehttp 14264 12640 "GET / HTTP/1.1" 200 13
WARNING 2023-09-19 17:02:12,986 log 14264 4072 Not Found: /ee
WARNING 2023-09-19 17:02:12,988 basehttp 14264 4072 "GET /ee HTTP/1.1" 404 2795
WARNING 2023-09-19 17:02:13,142 log 14264 10584 Not Found: /ee
WARNING 2023-09-19 17:02:13,143 basehttp 14264 10584 "GET /ee HTTP/1.1" 404 2795
ERROR 2023-09-19 17:02:19,452 log 14264 15160 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 17:02:19,458 basehttp 14264 15160 "GET /order_list HTTP/1.1" 500 67557
ERROR 2023-09-19 17:02:19,704 log 14264 10728 Internal Server Error: /order_list
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 38, in get_context_data
    context = super().get_context_data(**kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
ERROR 2023-09-19 17:02:19,718 basehttp 14264 10728 "GET /order_list HTTP/1.1" 500 66612
INFO 2023-09-20 13:29:34,103 autoreload 11944 2680 Watching for file changes with StatReloader
INFO 2023-09-20 13:30:10,836 autoreload 9300 9168 Watching for file changes with StatReloader
INFO 2023-09-20 13:30:21,401 views 9300 9236 Index page accessed
INFO 2023-09-20 13:30:21,510 basehttp 9300 9236 "GET / HTTP/1.1" 200 13
WARNING 2023-09-20 13:30:27,364 log 9300 9236 Not Found: /favicon.ico
WARNING 2023-09-20 13:30:27,379 basehttp 9300 9236 "GET /favicon.ico HTTP/1.1" 404 2997
INFO 2023-09-20 13:30:32,599 basehttp 9300 13780 "GET /product HTTP/1.1" 301 0
INFO 2023-09-20 13:30:33,317 basehttp 9300 8428 "GET /product/ HTTP/1.1" 200 1318
INFO 2023-09-20 13:30:37,229 basehttp 9300 9804 "GET /product/ HTTP/1.1" 200 1318
INFO 2023-09-20 13:30:47,402 basehttp 9300 14300 "POST /product/ HTTP/1.1" 200 1423
INFO 2023-09-20 13:30:47,601 basehttp 9300 3196 "GET /product/ HTTP/1.1" 200 1318
INFO 2023-09-20 13:33:33,262 basehttp 9300 7128 "POST /product/ HTTP/1.1" 200 1507
INFO 2023-09-20 13:33:35,729 basehttp 9300 272 "GET /product/ HTTP/1.1" 200 1402
ERROR 2023-09-20 13:33:47,399 log 9300 6716 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 62, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 13:33:47,426 basehttp 9300 6716 "POST /product/ HTTP/1.1" 500 150902
INFO 2023-09-20 13:33:48,078 basehttp 9300 14364 "GET /product/ HTTP/1.1" 200 1402
INFO 2023-09-20 13:33:50,388 basehttp 9300 14364 "GET /product/ HTTP/1.1" 200 1402
ERROR 2023-09-20 13:33:51,477 log 9300 6956 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 62, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 13:33:51,497 basehttp 9300 6956 "POST /product/ HTTP/1.1" 500 150902
INFO 2023-09-20 13:33:51,800 basehttp 9300 1036 "GET /product/ HTTP/1.1" 200 1402
INFO 2023-09-20 13:33:53,332 basehttp 9300 1036 "GET /product/ HTTP/1.1" 200 1402
INFO 2023-09-20 13:34:08,331 basehttp 9300 5268 "POST /product/ HTTP/1.1" 200 1453
INFO 2023-09-20 13:34:08,601 basehttp 9300 2980 "GET /product/ HTTP/1.1" 200 1348
ERROR 2023-09-20 13:34:18,788 log 9300 10380 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 62, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 13:34:18,798 basehttp 9300 10380 "POST /product/ HTTP/1.1" 500 150902
INFO 2023-09-20 13:34:19,187 basehttp 9300 10408 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 13:34:28,777 basehttp 9300 7180 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 13:40:46,567 autoreload 9300 9168 D:\Python_django\dz\myapp\urls.py changed, reloading.
INFO 2023-09-20 13:40:59,898 autoreload 8644 13472 Watching for file changes with StatReloader
INFO 2023-09-20 13:41:11,731 basehttp 8644 15660 "POST /product/ HTTP/1.1" 200 1423
INFO 2023-09-20 13:41:12,930 basehttp 8644 7212 "GET /product/ HTTP/1.1" 200 1318
WARNING 2023-09-20 13:55:27,405 log 8644 8744 Not Found: /update_image/
WARNING 2023-09-20 13:55:27,413 basehttp 8644 8744 "GET /update_image/ HTTP/1.1" 404 3178
WARNING 2023-09-20 13:55:28,748 log 8644 3648 Not Found: /update_image/
WARNING 2023-09-20 13:55:28,750 basehttp 8644 3648 "GET /update_image/ HTTP/1.1" 404 3178
INFO 2023-09-20 13:55:36,373 basehttp 8644 9260 "GET /upload HTTP/1.1" 301 0
INFO 2023-09-20 13:55:36,464 basehttp 8644 9392 "GET /upload/ HTTP/1.1" 200 597
INFO 2023-09-20 13:55:36,647 basehttp 8644 15556 "GET /upload/ HTTP/1.1" 200 597
INFO 2023-09-20 13:55:42,252 basehttp 8644 3684 "POST /upload/ HTTP/1.1" 200 597
INFO 2023-09-20 13:55:42,458 basehttp 8644 8368 "GET /upload/ HTTP/1.1" 200 597
WARNING 2023-09-20 13:56:21,222 log 8644 13140 Not Found: /docs
WARNING 2023-09-20 13:56:21,229 basehttp 8644 13140 "GET /docs HTTP/1.1" 404 3151
WARNING 2023-09-20 13:56:22,182 log 8644 14548 Not Found: /docs
WARNING 2023-09-20 13:56:22,184 basehttp 8644 14548 "GET /docs HTTP/1.1" 404 3151
INFO 2023-09-20 13:56:29,905 basehttp 8644 12184 "GET /product/ HTTP/1.1" 200 1318
INFO 2023-09-20 13:56:30,153 basehttp 8644 14248 "GET /product/ HTTP/1.1" 200 1318
INFO 2023-09-20 13:56:41,701 autoreload 8644 13472 D:\Python_django\dz\myapp\forms.py changed, reloading.
INFO 2023-09-20 13:56:45,653 autoreload 13136 10884 Watching for file changes with StatReloader
INFO 2023-09-20 13:56:46,328 basehttp 13136 15664 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 13:56:46,776 basehttp 13136 13016 "GET /product/ HTTP/1.1" 200 1173
ERROR 2023-09-20 13:56:54,573 log 13136 15772 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 59, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 13:56:54,589 basehttp 13136 15772 "POST /product/ HTTP/1.1" 500 150096
INFO 2023-09-20 13:56:55,000 basehttp 13136 2868 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 14:02:49,545 autoreload 15336 13176 Watching for file changes with StatReloader
INFO 2023-09-20 14:02:57,195 basehttp 15336 1460 "POST /product/ HTTP/1.1" 200 1218
INFO 2023-09-20 14:02:58,575 basehttp 15336 9444 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 14:02:59,876 basehttp 15336 1460 "POST /product/ HTTP/1.1" 200 1218
INFO 2023-09-20 14:03:00,047 basehttp 15336 9444 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 14:03:19,032 autoreload 15336 13176 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:03:23,992 autoreload 9084 2864 Watching for file changes with StatReloader
INFO 2023-09-20 14:03:28,423 basehttp 9084 6140 "POST /product/ HTTP/1.1" 200 1218
INFO 2023-09-20 14:03:29,050 basehttp 9084 3020 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 14:03:30,248 basehttp 9084 6140 "POST /product/ HTTP/1.1" 200 1218
INFO 2023-09-20 14:03:30,430 basehttp 9084 3020 "GET /product/ HTTP/1.1" 200 1173
INFO 2023-09-20 14:09:37,055 autoreload 9084 2864 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-20 14:09:44,160 autoreload 12164 16096 Watching for file changes with StatReloader
INFO 2023-09-20 14:10:30,581 autoreload 12164 16096 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-20 14:10:35,879 autoreload 16232 7608 Watching for file changes with StatReloader
INFO 2023-09-20 14:11:00,185 autoreload 16232 7608 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-20 14:11:02,666 autoreload 13892 14552 Watching for file changes with StatReloader
INFO 2023-09-20 14:13:34,429 autoreload 13892 14552 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:13:38,296 autoreload 3696 6784 Watching for file changes with StatReloader
INFO 2023-09-20 14:17:29,779 autoreload 3696 6784 D:\Python_django\dz\myapp\forms.py changed, reloading.
INFO 2023-09-20 14:17:33,988 autoreload 1816 3192 Watching for file changes with StatReloader
INFO 2023-09-20 14:22:08,154 autoreload 10936 1544 Watching for file changes with StatReloader
INFO 2023-09-20 14:22:22,186 basehttp 10936 12848 "POST /product/ HTTP/1.1" 200 1452
INFO 2023-09-20 14:22:22,186 basehttp 10936 2668 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:22:22,633 basehttp 10936 2668 "GET /product/ HTTP/1.1" 200 1348
ERROR 2023-09-20 14:22:28,812 log 10936 15092 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 62, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 14:22:28,823 basehttp 10936 15092 "POST /product/ HTTP/1.1" 500 151052
INFO 2023-09-20 14:22:29,404 basehttp 10936 2868 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:22:38,023 basehttp 10936 11556 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:24:04,149 autoreload 10936 1544 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:24:07,324 autoreload 14808 256 Watching for file changes with StatReloader
ERROR 2023-09-20 14:24:22,621 log 14808 10308 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 61, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1745, in as_sql
    value_rows = [
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1746, in <listcomp>
    [
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\fields\files.py", line 315, in pre_save
    if file and not file._committed:
AttributeError: 'tuple' object has no attribute '_committed'
ERROR 2023-09-20 14:24:22,636 basehttp 14808 10308 "POST /product/ HTTP/1.1" 500 129477
INFO 2023-09-20 14:24:26,949 basehttp 14808 15532 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:24:27,107 basehttp 14808 16192 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:25:05,190 autoreload 14808 256 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:25:09,388 autoreload 11320 8072 Watching for file changes with StatReloader
ERROR 2023-09-20 14:25:11,461 log 11320 12212 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: table myapp_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 61, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: table myapp_product has no column named image
ERROR 2023-09-20 14:25:11,471 basehttp 11320 12212 "POST /product/ HTTP/1.1" 500 151729
INFO 2023-09-20 14:25:13,189 basehttp 11320 8212 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:25:15,206 basehttp 11320 8212 "GET /product/ HTTP/1.1" 200 1348
INFO 2023-09-20 14:26:45,152 autoreload 11320 8072 D:\Python_django\dz\myapp\forms.py changed, reloading.
INFO 2023-09-20 14:27:06,847 autoreload 11004 8120 Watching for file changes with StatReloader
ERROR 2023-09-20 14:27:17,977 log 11004 840 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 61, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-20 14:27:17,995 basehttp 11004 840 "POST /product/ HTTP/1.1" 500 128145
INFO 2023-09-20 14:27:20,137 basehttp 11004 7912 "GET /product/ HTTP/1.1" 200 1241
ERROR 2023-09-20 14:27:35,535 log 11004 14664 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 61, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-20 14:27:35,762 basehttp 11004 14664 "POST /product/ HTTP/1.1" 500 128145
INFO 2023-09-20 14:27:36,975 basehttp 11004 3332 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:29:11,105 autoreload 2988 11132 Watching for file changes with StatReloader
WARNING 2023-09-20 14:29:18,296 log 2988 3528 Not Found: /docs
WARNING 2023-09-20 14:29:18,298 basehttp 2988 3528 "GET /docs HTTP/1.1" 404 3151
WARNING 2023-09-20 14:29:19,818 log 2988 4468 Not Found: /docs
WARNING 2023-09-20 14:29:19,820 basehttp 2988 4468 "GET /docs HTTP/1.1" 404 3151
INFO 2023-09-20 14:29:25,504 basehttp 2988 2936 "GET /upload/ HTTP/1.1" 200 597
INFO 2023-09-20 14:29:25,849 basehttp 2988 12884 "GET /upload/ HTTP/1.1" 200 597
INFO 2023-09-20 14:29:31,528 basehttp 2988 2936 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:29:31,704 basehttp 2988 12884 "GET /product/ HTTP/1.1" 200 1241
ERROR 2023-09-20 14:29:43,088 log 2988 3648 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 61, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-20 14:29:43,106 basehttp 2988 3648 "POST /product/ HTTP/1.1" 500 128148
INFO 2023-09-20 14:29:43,435 basehttp 2988 8440 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:30:50,156 autoreload 2988 11132 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:30:53,886 autoreload 16108 15468 Watching for file changes with StatReloader
ERROR 2023-09-20 14:31:02,737 log 16108 15376 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 58, in add_product
    image = form.cleaned_data['image']
KeyError: 'image'
ERROR 2023-09-20 14:31:02,740 basehttp 16108 15376 "POST /product/ HTTP/1.1" 500 69824
INFO 2023-09-20 14:31:04,929 basehttp 16108 12156 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:31:07,786 basehttp 16108 6612 "GET /product/ HTTP/1.1" 200 1241
ERROR 2023-09-20 14:31:09,546 log 16108 5492 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 58, in add_product
    image = form.cleaned_data['image']
KeyError: 'image'
ERROR 2023-09-20 14:31:09,548 basehttp 16108 5492 "POST /product/ HTTP/1.1" 500 69824
INFO 2023-09-20 14:31:09,735 basehttp 16108 6612 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:31:21,782 autoreload 16108 15468 D:\Python_django\dz\myapp\views.py changed, reloading.
INFO 2023-09-20 14:31:24,947 autoreload 6876 13124 Watching for file changes with StatReloader
INFO 2023-09-20 14:31:27,083 basehttp 6876 15880 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:31:29,957 basehttp 6876 15696 "GET /product/ HTTP/1.1" 200 1241
ERROR 2023-09-20 14:31:40,989 log 6876 6976 Internal Server Error: /product/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\dz\myapp\views.py", line 59, in add_product
    product.save()
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1020, in _save_table
    results = self._do_insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\base.py", line 1061, in _do_insert
    return manager._insert(
  File "D:\Python_django\venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Python_django\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1833, in execute_sql
    self.connection.ops.fetch_returned_insert_columns(
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\operations.py", line 213, in fetch_returned_insert_columns
    return cursor.fetchone()
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 97, in inner
    with self:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 98, in inner
    return func(*args, **kwargs)
django.db.utils.OperationalError: database is locked
ERROR 2023-09-20 14:31:41,013 basehttp 6876 6976 "POST /product/ HTTP/1.1" 500 128124
INFO 2023-09-20 14:31:41,224 basehttp 6876 9892 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:32:17,242 autoreload 6876 13124 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-20 14:32:22,660 autoreload 16316 8004 Watching for file changes with StatReloader
INFO 2023-09-20 14:32:46,686 autoreload 16316 8004 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-20 14:32:49,256 autoreload 7804 4120 Watching for file changes with StatReloader
INFO 2023-09-20 14:33:52,106 autoreload 13144 8816 Watching for file changes with StatReloader
INFO 2023-09-20 14:34:00,565 basehttp 13144 11824 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-20 14:34:03,250 basehttp 13144 15724 "GET /product/ HTTP/1.1" 200 1241
INFO 2023-09-24 21:42:28,588 autoreload 11636 15064 Watching for file changes with StatReloader
INFO 2023-09-24 21:42:32,761 basehttp 11636 8896 "GET /admin/myapp5/product/2/change/ HTTP/1.1" 302 0
INFO 2023-09-24 21:42:33,163 basehttp 11636 8896 "GET /admin/login/?next=/admin/myapp5/product/2/change/ HTTP/1.1" 200 4229
INFO 2023-09-24 21:42:34,749 basehttp 11636 15916 "GET /admin/login/?next=/admin/myapp5/product/2/change/ HTTP/1.1" 200 4229
INFO 2023-09-24 21:42:40,167 basehttp 11636 3680 "GET /admin HTTP/1.1" 301 0
INFO 2023-09-24 21:42:40,199 basehttp 11636 16204 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-09-24 21:42:40,232 basehttp 11636 16204 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-09-24 21:42:40,473 basehttp 11636 576 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
ERROR 2023-09-24 21:42:52,479 log 11636 7464 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\base.py", line 313, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Python_django\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\auth\views.py", line 109, in form_valid
    auth_login(self.request, form.get_user())
  File "D:\Python_django\venv\lib\site-packages\django\contrib\auth\__init__.py", line 118, in login
    request.session.cycle_key()
  File "D:\Python_django\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 304, in cycle_key
    self.create()
  File "D:\Python_django\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 54, in create
    self.save(must_create=True)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 85, in save
    with transaction.atomic(using=using):
  File "D:\Python_django\venv\lib\site-packages\django\db\transaction.py", line 263, in __exit__
    connection.commit()
  File "D:\Python_django\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\base.py", line 337, in commit
    self._commit()
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\base.py", line 312, in _commit
    with debug_transaction(self, "COMMIT"), self.wrap_database_errors:
  File "D:\Python_django\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python_django\venv\lib\site-packages\django\db\backends\base\base.py", line 313, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked
ERROR 2023-09-24 21:42:52,520 basehttp 11636 7464 "POST /admin/login/?next=/admin/ HTTP/1.1" 500 175657
INFO 2023-09-24 21:42:53,078 basehttp 11636 1772 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-09-24 22:13:06,651 autoreload 8028 8512 Watching for file changes with StatReloader
INFO 2023-09-24 22:13:17,416 views 8028 15164 Index page accessed
INFO 2023-09-24 22:13:17,443 basehttp 8028 15164 "GET / HTTP/1.1" 200 13
INFO 2023-09-24 22:13:18,230 views 8028 14348 Index page accessed
INFO 2023-09-24 22:13:18,231 basehttp 8028 14348 "GET / HTTP/1.1" 200 13
INFO 2023-09-24 22:13:42,616 views 8028 9140 Index page accessed
INFO 2023-09-24 22:13:42,619 basehttp 8028 9140 "GET / HTTP/1.1" 200 13
INFO 2023-09-24 22:13:42,761 views 8028 8452 Index page accessed
INFO 2023-09-24 22:13:42,775 basehttp 8028 8452 "GET / HTTP/1.1" 200 13
INFO 2023-09-24 22:13:49,550 basehttp 8028 15752 "GET /admin HTTP/1.1" 301 0
INFO 2023-09-24 22:13:49,618 basehttp 8028 15820 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-09-24 22:13:49,826 basehttp 8028 15820 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-09-24 22:13:50,196 basehttp 8028 11636 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
INFO 2023-09-24 22:13:53,724 basehttp 8028 15820 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2023-09-24 22:13:53,812 basehttp 8028 15820 "GET /admin/ HTTP/1.1" 200 5556
INFO 2023-09-24 22:13:54,011 basehttp 8028 11636 "GET /admin/ HTTP/1.1" 200 5556
INFO 2023-09-24 22:14:28,501 autoreload 8028 8512 D:\Python_django\dz\myproject\settings.py changed, reloading.
INFO 2023-09-24 22:14:33,258 autoreload 15284 13016 Watching for file changes with StatReloader
INFO 2023-09-24 22:14:34,385 basehttp 15284 1044 "GET /admin/ HTTP/1.1" 200 5852
INFO 2023-09-24 22:14:35,006 basehttp 15284 6476 "GET /admin/ HTTP/1.1" 200 5852
INFO 2023-09-25 06:56:02,242 autoreload 18104 8888 Watching for file changes with StatReloader
INFO 2023-09-25 06:56:13,150 views 18104 1284 Index page accessed
INFO 2023-09-25 06:56:13,152 basehttp 18104 1284 "GET / HTTP/1.1" 200 13
INFO 2023-09-25 06:56:15,738 views 18104 11184 Index page accessed
INFO 2023-09-25 06:56:15,740 basehttp 18104 11184 "GET / HTTP/1.1" 200 13
INFO 2023-09-25 07:06:25,733 basehttp 18104 17036 "GET /admin/ HTTP/1.1" 200 5852
INFO 2023-09-25 07:06:26,656 basehttp 18104 18416 "GET /admin/ HTTP/1.1" 200 5852
INFO 2023-09-25 07:20:02,840 autoreload 18104 8888 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:20:09,039 autoreload 9516 8860 Watching for file changes with StatReloader
INFO 2023-09-25 07:20:25,992 autoreload 9516 8860 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:20:31,919 autoreload 2116 6956 Watching for file changes with StatReloader
INFO 2023-09-25 07:20:35,643 autoreload 2116 6956 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:20:37,248 autoreload 13376 3340 Watching for file changes with StatReloader
INFO 2023-09-25 07:20:49,553 autoreload 13376 3340 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:20:50,941 autoreload 9784 2692 Watching for file changes with StatReloader
INFO 2023-09-25 07:20:54,754 basehttp 9784 10464 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:20:56,745 basehttp 9784 12140 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:20:58,612 basehttp 9784 13568 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:20:58,946 basehttp 9784 13568 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:20:59,151 basehttp 9784 12140 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:21:01,240 basehttp 9784 13588 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:01,403 basehttp 9784 14396 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:02,501 basehttp 9784 13588 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:21:02,596 basehttp 9784 13588 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:02,741 basehttp 9784 14396 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:21:04,174 basehttp 9784 13588 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:04,311 basehttp 9784 14396 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:05,005 basehttp 9784 13588 "GET /admin/myapp/order/ HTTP/1.1" 200 8399
INFO 2023-09-25 07:21:05,079 basehttp 9784 13588 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:05,251 basehttp 9784 14396 "GET /admin/myapp/order/ HTTP/1.1" 200 8399
INFO 2023-09-25 07:21:08,426 basehttp 9784 16180 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:08,580 basehttp 9784 16808 "GET /admin/ HTTP/1.1" 200 7407
INFO 2023-09-25 07:21:19,658 basehttp 9784 9740 "GET /admin/myapp/order/add/ HTTP/1.1" 200 14453
INFO 2023-09-25 07:21:19,770 basehttp 9784 9740 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:20,053 basehttp 9784 12128 "GET /admin/myapp/order/add/ HTTP/1.1" 200 14453
INFO 2023-09-25 07:21:28,206 basehttp 9784 10852 "GET /admin/myapp/product/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6377
INFO 2023-09-25 07:21:28,351 basehttp 9784 10852 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:28,756 basehttp 9784 8600 "GET /admin/myapp/product/add/?_to_field=id&_popup=1 HTTP/1.1" 200 6377
INFO 2023-09-25 07:21:34,591 basehttp 9784 5216 "POST /admin/myapp/order/add/ HTTP/1.1" 302 0
INFO 2023-09-25 07:21:34,648 basehttp 9784 5216 "GET /admin/myapp/order/ HTTP/1.1" 200 10050
INFO 2023-09-25 07:21:34,739 basehttp 9784 5216 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:34,971 basehttp 9784 2960 "GET /admin/myapp/order/ HTTP/1.1" 200 9746
INFO 2023-09-25 07:21:36,897 basehttp 9784 10452 "GET /admin/myapp/order/1/change/ HTTP/1.1" 200 14986
INFO 2023-09-25 07:21:36,972 basehttp 9784 10452 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:37,221 basehttp 9784 10684 "GET /admin/myapp/order/1/change/ HTTP/1.1" 200 14986
INFO 2023-09-25 07:21:39,293 basehttp 9784 10452 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:21:39,378 basehttp 9784 10452 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:21:39,528 basehttp 9784 10684 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:22:53,428 autoreload 9784 2692 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-25 07:22:57,552 autoreload 13272 12528 Watching for file changes with StatReloader
INFO 2023-09-25 07:23:00,149 autoreload 13272 12528 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-25 07:23:02,353 autoreload 1504 12816 Watching for file changes with StatReloader
INFO 2023-09-25 07:23:36,623 autoreload 8096 7784 Watching for file changes with StatReloader
INFO 2023-09-25 07:23:42,266 basehttp 8096 16132 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:23:42,825 basehttp 8096 16132 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:23:43,983 basehttp 8096 16776 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:23:45,263 basehttp 8096 16132 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:23:45,357 basehttp 8096 16132 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:23:45,667 basehttp 8096 17384 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:23:49,176 basehttp 8096 8944 "GET /admin/myapp/product/7/change/ HTTP/1.1" 200 11429
INFO 2023-09-25 07:23:49,398 basehttp 8096 8944 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:23:49,508 basehttp 8096 17384 "GET /admin/myapp/product/7/change/ HTTP/1.1" 200 11429
INFO 2023-09-25 07:23:55,210 basehttp 8096 8492 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:23:55,275 basehttp 8096 8492 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:23:55,434 basehttp 8096 5928 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:24:47,237 autoreload 8096 7784 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:24:49,391 autoreload 14268 13784 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:03,086 autoreload 14268 13784 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:09,614 autoreload 14472 14456 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:11,105 autoreload 14472 14456 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:13,743 autoreload 13428 7252 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:19,467 autoreload 13428 7252 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:23,346 autoreload 16732 9404 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:25,288 autoreload 16732 9404 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:29,096 autoreload 9768 17852 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:36,018 autoreload 9768 17852 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:38,097 autoreload 17776 17300 Watching for file changes with StatReloader
INFO 2023-09-25 07:25:40,007 autoreload 17776 17300 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:25:41,566 autoreload 11260 15316 Watching for file changes with StatReloader
INFO 2023-09-25 07:26:06,605 autoreload 11260 15316 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:26:08,516 autoreload 6672 11304 Watching for file changes with StatReloader
INFO 2023-09-25 07:26:16,902 basehttp 6672 1780 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:26:17,375 basehttp 6672 1780 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:26:17,685 basehttp 6672 3060 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:26:52,699 autoreload 6672 11304 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:26:55,692 autoreload 8476 9544 Watching for file changes with StatReloader
INFO 2023-09-25 07:27:03,430 autoreload 8476 9544 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:27:05,318 autoreload 13600 10996 Watching for file changes with StatReloader
INFO 2023-09-25 07:27:22,010 autoreload 13600 10996 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:27:23,358 autoreload 13888 7956 Watching for file changes with StatReloader
INFO 2023-09-25 07:27:26,751 basehttp 13888 18424 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:27:27,293 basehttp 13888 18424 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:27:28,023 basehttp 13888 15472 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:27:32,940 basehttp 13888 9396 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:27:33,107 basehttp 13888 9396 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:27:33,266 basehttp 13888 16884 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:27:34,817 basehttp 13888 9396 "GET /admin/myapp/order/ HTTP/1.1" 200 9746
INFO 2023-09-25 07:27:34,897 basehttp 13888 9396 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:27:35,040 basehttp 13888 16884 "GET /admin/myapp/order/ HTTP/1.1" 200 9746
INFO 2023-09-25 07:27:36,879 basehttp 13888 9396 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:27:36,942 basehttp 13888 9396 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:27:37,094 basehttp 13888 16884 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:27:49,778 autoreload 13888 7956 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:27:52,031 autoreload 15464 3300 Watching for file changes with StatReloader
INFO 2023-09-25 07:27:54,015 autoreload 15464 3300 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:28:00,025 autoreload 14608 11200 Watching for file changes with StatReloader
INFO 2023-09-25 07:28:03,168 autoreload 14608 11200 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:28:05,813 autoreload 16712 3876 Watching for file changes with StatReloader
INFO 2023-09-25 07:28:08,591 autoreload 16712 3876 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 07:28:11,527 autoreload 9804 16816 Watching for file changes with StatReloader
INFO 2023-09-25 07:28:15,057 basehttp 9804 4120 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:28:15,596 basehttp 9804 4120 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:28:16,387 basehttp 9804 18164 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:28:18,762 basehttp 9804 14216 "GET /admin/myapp/order/ HTTP/1.1" 200 9746
INFO 2023-09-25 07:28:18,853 basehttp 9804 14216 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:28:19,025 basehttp 9804 18164 "GET /admin/myapp/order/ HTTP/1.1" 200 9746
INFO 2023-09-25 07:28:23,045 basehttp 9804 14180 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:28:23,214 basehttp 9804 14180 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:28:23,377 basehttp 9804 9036 "GET /admin/myapp/client/ HTTP/1.1" 200 13202
INFO 2023-09-25 07:28:25,011 basehttp 9804 14180 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:28:25,087 basehttp 9804 14180 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:28:25,221 basehttp 9804 9036 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:28:25,793 basehttp 9804 14180 "GET /admin/myapp/product/18/change/ HTTP/1.1" 200 11412
INFO 2023-09-25 07:28:25,906 basehttp 9804 14180 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:28:26,163 basehttp 9804 15988 "GET /admin/myapp/product/18/change/ HTTP/1.1" 200 11412
INFO 2023-09-25 07:28:27,639 basehttp 9804 8032 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:28:27,827 basehttp 9804 15988 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:30:15,536 autoreload 17984 11708 Watching for file changes with StatReloader
INFO 2023-09-25 07:33:27,221 basehttp 17984 16520 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11431
INFO 2023-09-25 07:33:27,495 basehttp 17984 16520 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:33:28,277 basehttp 17984 13004 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11431
INFO 2023-09-25 07:33:37,704 basehttp 17984 14448 "POST /admin/myapp/product/14/change/ HTTP/1.1" 302 0
INFO 2023-09-25 07:33:37,802 basehttp 17984 14448 "GET /admin/myapp/product/ HTTP/1.1" 200 13621
INFO 2023-09-25 07:33:37,995 basehttp 17984 14448 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:33:38,224 basehttp 17984 13184 "GET /admin/myapp/product/ HTTP/1.1" 200 13399
INFO 2023-09-25 07:33:39,851 basehttp 17984 14448 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11431
INFO 2023-09-25 07:33:39,965 basehttp 17984 14448 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 07:33:40,152 basehttp 17984 13184 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11431
INFO 2023-09-25 09:45:18,379 autoreload 6020 15912 Watching for file changes with StatReloader
INFO 2023-09-25 09:45:30,106 basehttp 6020 15532 "GET /admin/myapp/client/add/ HTTP/1.1" 200 11125
INFO 2023-09-25 09:45:30,651 basehttp 6020 15532 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:45:30,924 basehttp 6020 1040 "GET /admin/myapp/client/add/ HTTP/1.1" 200 11125
INFO 2023-09-25 09:46:12,512 basehttp 6020 17048 "POST /admin/myapp/client/add/ HTTP/1.1" 302 0
INFO 2023-09-25 09:46:12,708 basehttp 6020 17048 "GET /admin/myapp/client/ HTTP/1.1" 200 13729
INFO 2023-09-25 09:46:12,847 basehttp 6020 17048 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:46:13,164 basehttp 6020 13076 "GET /admin/myapp/client/ HTTP/1.1" 200 13466
INFO 2023-09-25 09:46:52,449 autoreload 6020 15912 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-25 09:46:58,601 autoreload 8180 6476 Watching for file changes with StatReloader
INFO 2023-09-25 09:47:57,520 autoreload 8180 6476 D:\Python_django\dz\myapp\models.py changed, reloading.
INFO 2023-09-25 09:48:00,715 autoreload 856 14232 Watching for file changes with StatReloader
INFO 2023-09-25 09:48:10,559 basehttp 856 15784 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 09:48:11,178 basehttp 856 15784 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:48:11,897 basehttp 856 9124 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 09:55:09,558 basehttp 856 10120 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:55:09,682 basehttp 856 10120 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:55:10,557 basehttp 856 15540 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:55:11,544 basehttp 856 10120 "GET /admin/myapp/product/16/change/ HTTP/1.1" 200 11409
INFO 2023-09-25 09:55:11,695 basehttp 856 10120 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:55:11,849 basehttp 856 15540 "GET /admin/myapp/product/16/change/ HTTP/1.1" 200 11409
INFO 2023-09-25 09:55:13,980 basehttp 856 10120 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:55:14,171 basehttp 856 15540 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:55:15,174 basehttp 856 10120 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11401
INFO 2023-09-25 09:55:15,247 basehttp 856 10120 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:55:15,415 basehttp 856 5352 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11401
INFO 2023-09-25 09:56:11,146 autoreload 856 14232 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:56:14,338 autoreload 17272 17592 Watching for file changes with StatReloader
INFO 2023-09-25 09:56:35,406 autoreload 17272 17592 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:56:37,254 autoreload 16708 1944 Watching for file changes with StatReloader
INFO 2023-09-25 09:56:41,908 basehttp 16708 17396 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:56:42,382 basehttp 16708 17396 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:56:42,991 basehttp 16708 5928 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:56:44,547 basehttp 16708 17396 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:56:46,092 basehttp 16708 5244 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:56:47,549 basehttp 16708 1044 "GET /admin/myapp/product/ HTTP/1.1" 200 13211
INFO 2023-09-25 09:57:00,111 autoreload 16708 1944 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:57:03,076 autoreload 6728 8176 Watching for file changes with StatReloader
INFO 2023-09-25 09:57:06,478 basehttp 6728 16184 "GET /admin/myapp/product/ HTTP/1.1" 200 14662
INFO 2023-09-25 09:57:06,556 basehttp 6728 16184 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:57:06,694 basehttp 6728 15644 "GET /admin/myapp/product/ HTTP/1.1" 200 14662
INFO 2023-09-25 09:57:41,654 autoreload 6728 8176 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:57:43,054 autoreload 844 11256 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:08,622 autoreload 844 11256 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:10,627 autoreload 10236 8940 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:18,443 autoreload 10236 8940 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:19,513 autoreload 10244 14852 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:26,381 basehttp 10244 12988 "GET /admin/myapp/product/ HTTP/1.1" 200 15452
INFO 2023-09-25 09:58:26,990 basehttp 10244 12988 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:58:27,608 basehttp 10244 15904 "GET /admin/myapp/product/ HTTP/1.1" 200 15452
INFO 2023-09-25 09:58:37,971 autoreload 10244 14852 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:39,397 autoreload 17412 17704 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:44,415 autoreload 17412 17704 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:46,124 autoreload 12792 11612 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:52,158 autoreload 12792 11612 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:53,669 autoreload 16732 11260 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:55,439 autoreload 16732 11260 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:58:56,339 autoreload 15932 5968 Watching for file changes with StatReloader
INFO 2023-09-25 09:58:58,966 basehttp 15932 17360 "GET /admin/myapp/product/ HTTP/1.1" 200 17200
INFO 2023-09-25 09:58:59,156 basehttp 15932 17360 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 09:58:59,646 basehttp 15932 3884 "GET /admin/myapp/product/ HTTP/1.1" 200 17200
INFO 2023-09-25 09:59:34,448 autoreload 15932 5968 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:59:38,983 autoreload 17120 8848 Watching for file changes with StatReloader
INFO 2023-09-25 09:59:41,751 autoreload 17120 8848 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 09:59:42,843 autoreload 14408 9664 Watching for file changes with StatReloader
INFO 2023-09-25 09:59:58,431 autoreload 14408 9664 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:02,316 autoreload 10108 2640 Watching for file changes with StatReloader
INFO 2023-09-25 10:00:08,140 autoreload 10108 2640 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:12,936 autoreload 16760 6064 Watching for file changes with StatReloader
INFO 2023-09-25 10:00:38,992 autoreload 16760 6064 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:43,012 autoreload 14380 1468 Watching for file changes with StatReloader
INFO 2023-09-25 10:00:45,838 autoreload 14380 1468 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:48,000 autoreload 16424 12468 Watching for file changes with StatReloader
INFO 2023-09-25 10:00:51,658 autoreload 16424 12468 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:53,459 autoreload 17188 16464 Watching for file changes with StatReloader
INFO 2023-09-25 10:00:56,366 autoreload 17188 16464 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:00:57,455 autoreload 7692 4536 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:01,317 autoreload 7692 4536 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:03,073 autoreload 14432 9020 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:05,887 autoreload 14432 9020 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:06,822 autoreload 1448 17112 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:11,735 autoreload 1448 17112 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:12,950 autoreload 1688 8384 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:17,059 autoreload 1688 8384 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:18,372 autoreload 5348 17128 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:19,799 autoreload 5348 17128 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:21,223 autoreload 16444 9368 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:29,864 autoreload 16444 9368 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:31,725 autoreload 13096 14816 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:43,194 autoreload 13096 14816 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:45,341 autoreload 11020 13964 Watching for file changes with StatReloader
INFO 2023-09-25 10:01:47,928 autoreload 11020 13964 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:01:48,850 autoreload 17152 12768 Watching for file changes with StatReloader
INFO 2023-09-25 10:02:12,987 autoreload 17152 12768 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:02:17,691 autoreload 13596 7524 Watching for file changes with StatReloader
INFO 2023-09-25 10:02:31,165 autoreload 13596 7524 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:02:33,263 autoreload 13836 6472 Watching for file changes with StatReloader
INFO 2023-09-25 10:02:35,084 autoreload 13836 6472 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 10:02:36,495 autoreload 2852 16712 Watching for file changes with StatReloader
INFO 2023-09-25 10:02:47,443 basehttp 2852 10424 "GET /admin/myapp/product/ HTTP/1.1" 200 17764
INFO 2023-09-25 10:02:47,976 basehttp 2852 10424 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 10:02:48,469 basehttp 2852 12944 "GET /admin/myapp/product/ HTTP/1.1" 200 17764
INFO 2023-09-25 10:02:53,844 basehttp 2852 16008 "POST /admin/myapp/product/ HTTP/1.1" 302 0
INFO 2023-09-25 10:02:53,900 basehttp 2852 16008 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 10:02:53,984 basehttp 2852 16008 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 10:02:54,176 basehttp 2852 5320 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 10:02:56,774 basehttp 2852 5976 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 10:02:56,871 basehttp 2852 5976 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 10:02:57,026 basehttp 2852 2708 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 11:36:17,833 basehttp 2852 9328 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:36:18,177 basehttp 2852 9328 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:36:18,731 basehttp 2852 16596 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:36:20,353 basehttp 2852 9328 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11401
INFO 2023-09-25 11:36:20,508 basehttp 2852 9328 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:36:20,655 basehttp 2852 16596 "GET /admin/myapp/product/14/change/ HTTP/1.1" 200 11401
INFO 2023-09-25 11:37:37,219 autoreload 2852 16712 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:37:48,572 autoreload 5232 16504 Watching for file changes with StatReloader
INFO 2023-09-25 11:37:52,233 autoreload 5232 16504 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:37:54,774 autoreload 18320 17092 Watching for file changes with StatReloader
INFO 2023-09-25 11:37:57,354 autoreload 18320 17092 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:37:59,015 autoreload 9228 6876 Watching for file changes with StatReloader
INFO 2023-09-25 11:38:21,479 autoreload 9228 6876 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:38:23,433 autoreload 3996 6616 Watching for file changes with StatReloader
INFO 2023-09-25 11:38:27,288 autoreload 3996 6616 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:38:29,040 autoreload 1892 12300 Watching for file changes with StatReloader
INFO 2023-09-25 11:38:30,951 autoreload 1892 12300 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:38:32,182 autoreload 11504 8072 Watching for file changes with StatReloader
INFO 2023-09-25 11:42:58,853 autoreload 16988 16112 Watching for file changes with StatReloader
INFO 2023-09-25 11:43:13,512 basehttp 16988 16592 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:43:14,015 basehttp 16988 16592 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:43:14,912 basehttp 16988 14388 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
ERROR 2023-09-25 11:43:21,290 log 16988 8588 Internal Server Error: /admin/myapp/product/16/change/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\Python_django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\Python_django\venv\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (price, quantity) specified for Product

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (price, quantity) specified for Product. Check fields/fieldsets/exclude attributes of class ProductAdmin.
ERROR 2023-09-25 11:43:21,298 basehttp 16988 8588 "GET /admin/myapp/product/16/change/ HTTP/1.1" 500 132896
ERROR 2023-09-25 11:43:21,697 log 16988 12872 Internal Server Error: /admin/myapp/product/16/change/
Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
  File "D:\Python_django\venv\lib\site-packages\django\forms\models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "D:\Python_django\venv\lib\site-packages\django\forms\models.py", line 321, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (price, quantity) specified for Product

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Python_django\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
  File "D:\Python_django\venv\lib\site-packages\django\contrib\admin\options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (price, quantity) specified for Product. Check fields/fieldsets/exclude attributes of class ProductAdmin.
ERROR 2023-09-25 11:43:21,707 basehttp 16988 12872 "GET /admin/myapp/product/16/change/ HTTP/1.1" 500 131780
INFO 2023-09-25 11:43:24,346 basehttp 16988 8896 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:43:24,842 basehttp 16988 3420 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:44:02,454 autoreload 15076 2748 Watching for file changes with StatReloader
INFO 2023-09-25 11:44:08,595 basehttp 15076 13388 "GET /admin/myapp/product/15/change/ HTTP/1.1" 200 12487
INFO 2023-09-25 11:44:09,968 basehttp 15076 11556 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:44:10,722 basehttp 15076 13388 "GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
INFO 2023-09-25 11:44:11,027 basehttp 15076 14192 "GET /admin/myapp/product/15/change/ HTTP/1.1" 200 12487
INFO 2023-09-25 11:44:25,512 basehttp 15076 9644 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 11:44:25,664 basehttp 15076 9644 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:44:25,845 basehttp 15076 15432 "GET /admin/myapp/client/ HTTP/1.1" 200 12741
INFO 2023-09-25 11:51:31,694 autoreload 15044 15464 Watching for file changes with StatReloader
INFO 2023-09-25 11:51:41,815 basehttp 15044 5068 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:51:43,118 basehttp 15044 5068 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:51:44,677 basehttp 15044 2676 "GET /admin/myapp/product/ HTTP/1.1" 200 17762
INFO 2023-09-25 11:51:51,771 basehttp 15044 11252 "GET /admin/myapp/client/ HTTP/1.1" 200 17167
INFO 2023-09-25 11:51:51,943 basehttp 15044 11252 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:51:52,113 basehttp 15044 17004 "GET /admin/myapp/client/ HTTP/1.1" 200 17167
INFO 2023-09-25 11:52:00,436 basehttp 15044 17856 "GET /admin/myapp/client/16/change/ HTTP/1.1" 200 12308
INFO 2023-09-25 11:52:00,602 basehttp 15044 17856 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:52:00,785 basehttp 15044 15088 "GET /admin/myapp/client/16/change/ HTTP/1.1" 200 12308
INFO 2023-09-25 11:52:49,556 autoreload 15044 15464 D:\Python_django\dz\myapp\admin.py changed, reloading.
INFO 2023-09-25 11:52:52,186 autoreload 2616 10424 Watching for file changes with StatReloader
INFO 2023-09-25 11:52:55,225 basehttp 2616 10376 "GET /admin/myapp/client/16/change/ HTTP/1.1" 200 12308
INFO 2023-09-25 11:52:56,124 basehttp 2616 10376 "GET /admin/jsi18n/ HTTP/1.1" 200 16066
INFO 2023-09-25 11:52:56,781 basehttp 2616 11748 "GET /admin/myapp/client/16/change/ HTTP/1.1" 200 12308
